import { useCallback, useEffect, useState } from 'react'
import type { WorkspaceId } from '../types'
import type { ReportData } from '../lib/reportBuilder'
import { fetchIntelligenceReports, type IntelligenceReportDoc } from '../lib/api/misc'
import { toReportData } from '../lib/intelligenceReport'

export interface ReportHistoryEntry {
  id: string
  data: ReportData
  /** The server document; present for every report generated by the backend. */
  doc?: IntelligenceReportDoc
}

// Generated reports are stored server-side (ai_reports) so history follows
// the workspace instead of the browser. Generation itself stores the row; the
// hook only mirrors it into the list.
export function useReportHistory(workspaceId: WorkspaceId) {
  const [entries, setEntries] = useState<ReportHistoryEntry[]>([])

  useEffect(() => {
    let cancelled = false
    if (!workspaceId) {
      setEntries([])
      return
    }
    fetchIntelligenceReports(workspaceId)
      .then((rows) => !cancelled && setEntries(rows.map((r) => ({ id: r.id, data: toReportData(r.report), doc: r.report }))))
      .catch(() => !cancelled && setEntries([]))
    return () => {
      cancelled = true
    }
  }, [workspaceId])

  const addEntry = useCallback((id: string, doc: IntelligenceReportDoc) => {
    setEntries((prev) => [{ id, data: toReportData(doc), doc }, ...prev.filter((e) => e.id !== id)])
  }, [])

  return { entries, addEntry }
}
