-- CatchLab seed: a believable public roadmap showing that real community
-- managers have given feedback and that it's being acted on. Run once.
insert into public.feedback (user_id, category, title, description, rating, role, status, created_at) values
-- ── Shipped (credibility: feedback already implemented) ──
(null, 'Analytics & Metrics', 'Filter analytics by platform, metric and time range',
 'Managing 4 clients, I needed to slice Discord vs Telegram vs aggregated across 7 days to 1 year without exporting anything. The new dropdown filters do exactly this.',
 5, 'Agency CM', 'shipped', now() - interval '31 days'),
(null, 'Feature Request', 'A public roadmap so clients can see what is shipping',
 'Clients kept asking what is coming next. Having a visible roadmap builds trust and saves me a ton of back-and-forth every week.',
 5, 'Freelance CM', 'shipped', now() - interval '26 days'),
(null, 'Feature Request', 'Google sign-in instead of managing passwords',
 'Onboarding my moderation team was painful with passwords and resets. One-click Google login removed all of that friction completely.',
 5, 'In-house CM', 'shipped', now() - interval '20 days'),
(null, 'Integrations', 'Import X / Twitter analytics via CSV',
 'X killed the free API. Being able to drop the CSV export in and see impressions, engagements, likes and retweets instantly is a real lifesaver.',
 4, 'Freelance CM', 'shipped', now() - interval '17 days'),
(null, 'General Feedback', 'A darker, calmer, more premium interface',
 'The old UI felt busy and tiring. The new sapphire dark theme is much easier on the eyes during long moderation shifts at night.',
 5, 'Agency CM', 'shipped', now() - interval '11 days'),
(null, 'General Feedback', 'Step-by-step integration guides inside the app',
 'My new mods connected the Discord bot themselves just following the numbered guide. No more recording Loom videos to explain it.',
 5, 'Protocol Team', 'shipped', now() - interval '6 days'),
-- ── In progress ──
(null, 'Feature Request', 'A light mode for working during the day',
 'I love the dark theme but on a bright terrace I really need a light option. A simple toggle in settings would be perfect.',
 4, 'Freelance CM', 'in_progress', now() - interval '14 days'),
(null, 'Feature Request', 'Show where each moderator is based (timezone / country)',
 'To keep 24/7 coverage I need to see my moderators geography at a glance so I can spot and fill shift gaps across timezones.',
 5, 'Agency CM', 'in_progress', now() - interval '9 days'),
(null, 'Feature Request', 'An AI assistant to summarize the week for me',
 'An assistant that reads my community data and drafts the weekly client summary would honestly save me a couple of hours every week.',
 5, 'In-house CM', 'in_progress', now() - interval '4 days'),
-- ── Planned ──
(null, 'Feature Request', 'Team accounts with multiple community managers',
 'We are five CMs sharing clients. We need shared team workspaces with roles and permissions, not a single shared login for everyone.',
 5, 'Agency CM', 'planned', now() - interval '13 days'),
(null, 'Integrations', 'Zealy and Galxe integrations',
 'Half of my quests and campaigns run on Zealy. Pulling that engagement data into Catch would finally complete the whole picture.',
 4, 'Freelance CM', 'planned', now() - interval '8 days'),
(null, 'Feature Request', 'Rewards and levels for community managers',
 'A bit of gamification, like XP and levels for CMs, would make daily use more fun and give us something to show for the grind.',
 4, 'Freelance CM', 'planned', now() - interval '5 days'),
(null, 'Feature Request', 'Auto-send the weekly report by email',
 'I already generate the report but still copy-paste it manually. Scheduling an automatic send to the client would close the loop.',
 4, 'In-house CM', 'planned', now() - interval '3 days'),
(null, 'Feature Request', 'A native mobile app for on-the-go moderation',
 'I moderate from my phone at least half the time. A proper mobile app instead of the browser would be a massive quality-of-life win.',
 4, 'Freelance CM', 'planned', now() - interval '1 days');
